import { defineType } from "sanity";

export default defineType({
  name: "recoveryCode",
  title: "Recovery Code",
  type: "document",
  fields: [
    {
      name: "userId",
      title: "User ID",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "codeHash",
      title: "Code Hash",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "expiresAt",
      title: "Expires At",
      type: "datetime",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "used",
      title: "Used",
      type: "boolean",
      initialValue: false,
    },
    {
      name: "usedAt",
      title: "Used At",
      type: "datetime",
    },
    {
      name: "attempts",
      title: "Attempts",
      type: "number",
      initialValue: 0,
    },
    {
      name: "generatedBy",
      title: "Generated By",
      type: "string",
    },
    {
      name: "createdAt",
      title: "Created At",
      type: "datetime",
    },
  ],
  preview: {
    select: {
      title: "codeHash",
    },
  },
});